---
- name: Deploy Kubernetes + Cri-Dockerd + Grafana
  hosts: grafana-servers
  become: yes
  vars_files:
    - group_vars/grafana-servers.yml

  tasks:
    # --- Atualizar o sistema ---
    - name: Atualizar pacotes do sistema
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    # --- Instalar dependências básicas ---
    - name: Instalar pacotes necessários
      apt:
        name:
          - curl
          - wget
          - tar
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
        state: present

    # --- Instalar cri-dockerd ---
    - name: Criar diretório temporário para cri-dockerd
      file:
        path: /tmp/cri-dockerd
        state: directory

    - name: Baixar última versão do cri-dockerd
      get_url:
        url: "https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.1/cri-dockerd-0.3.1.amd64.tgz"
        dest: /tmp/cri-dockerd/cri-dockerd.tgz
        validate_certs: yes

    - name: Extrair cri-dockerd
      unarchive:
        src: /tmp/cri-dockerd/cri-dockerd.tgz
        dest: /usr/local/bin/
        remote_src: yes

    - name: Ajustar permissões do cri-dockerd
      file:
        path: /usr/local/bin/cri-dockerd
        mode: '0755'

    # --- Configurar systemd para cri-dockerd ---
    - name: Baixar arquivo de serviço cri-dockerd.service
      get_url:
        url: "https://raw.githubusercontent.com/Mirantis/cri-dockerd/main/packaging/systemd/cri-dockerd.service"
        dest: /etc/systemd/system/cri-docker.service
        validate_certs: yes

    - name: Baixar arquivo de socket cri-dockerd.socket
      get_url:
        url: "https://raw.githubusercontent.com/Mirantis/cri-dockerd/main/packaging/systemd/cri-dockerd.socket"
        dest: /etc/systemd/system/cri-docker.socket
        validate_certs: yes

    - name: Habilitar e iniciar cri-dockerd
      systemd:
        name: cri-docker
        state: started
        enabled: yes
        daemon_reload: yes

    # --- Instalar Kubernetes ---
    - name: Adicionar chave GPG do Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adicionar repositório Kubernetes
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Instalar kubeadm, kubelet e kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Segurar versões do Kubernetes para não atualizar automaticamente
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        allow_unauthenticated: yes
        force: yes

    # --- Instalar Grafana ---
    - name: Adicionar repositório Grafana
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Adicionar chave GPG do Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Habilitar e iniciar Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes
        daemon_reload: yes
