---
- name: Grafana's Deploy + Kubernetes + cri-dockerd
  hosts: grafana-servers
  become: yes
  vars_files:
    - group_vars/grafana-servers.yml

  tasks:
    # --- Atualizar pacotes ---
    - name: Atualizar repositórios e pacotes
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    # --- Instalar dependências básicas ---
    - name: Instalar pacotes necessários
      apt:
        name:
          - curl
          - wget
          - vim
          - git
          - software-properties-common
        state: present

    # --- Instalar Docker ---
    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    # --- Instalar cri-dockerd via copy (fix 404) ---
    - name: Criar arquivo cri-docker.service
      copy:
        dest: /etc/systemd/system/cri-docker.service
        content: |
          [Unit]
          Description=CRI Docker Daemon
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/cri-dockerd --container-runtime-endpoint fd://
          Restart=always
          RestartSec=5s

          [Install]
          WantedBy=multi-user.target

    - name: Criar arquivo cri-docker.socket
      copy:
        dest: /etc/systemd/system/cri-docker.socket
        content: |
          [Unit]
          Description=CRI Docker Socket

          [Socket]
          ListenStream=/var/run/cri-dockerd.sock
          SocketMode=0660
          SocketUser=root
          SocketGroup=docker

          [Install]
          WantedBy=sockets.target

    - name: Habilitar e iniciar cri-dockerd
      systemd:
        name: cri-docker
        state: started
        enabled: yes
        daemon_reload: yes

    # --- Instalar kubeadm, kubelet e kubectl ---
    - name: Adicionar chave GPG do Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adicionar repositório Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Instalar kubeadm, kubelet e kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Marcar pacotes kube* para não atualizar automaticamente
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: hold

    # --- Instalar Nginx (para ingress ou teste) ---
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
