---
- name: Configurar cluster EKS
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    kubeconfig_path: "~/.kube/config"  # Caminho do kubeconfig gerado pelo Terraform/EKS
    grafana_namespace: "grafana"
    grafana_release_name: "grafana"
    grafana_chart: "grafana/grafana"
    grafana_chart_version: "6.56.2"  # exemplo, pode atualizar
    grafana_values_file: "./grafana-values.yml"

  tasks:

    - name: Instalar kubectl
      ansible.builtin.package:
        name: kubectl
        state: present

    - name: Instalar Helm
      ansible.builtin.package:
        name: helm
        state: present

    - name: Configurar contexto do kubectl
      community.kubernetes.k8s_auth:
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Criar namespace do Grafana
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ grafana_namespace }}"
        state: present
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Deploy Grafana via Helm
      community.kubernetes.helm:
        name: "{{ grafana_release_name }}"
        chart_ref: "{{ grafana_chart }}"
        chart_version: "{{ grafana_chart_version }}"
        release_namespace: "{{ grafana_namespace }}"
        values_file: "{{ grafana_values_file }}"
        kubeconfig: "{{ kubeconfig_path }}"
        state: present

    - name: Verificar pods do Grafana
      community.kubernetes.k8s_info:
        kind: Pod
        namespace: "{{ grafana_namespace }}"
        kubeconfig: "{{ kubeconfig_path }}"
      register: grafana_pods

    - name: Mostrar status dos pods do Grafana
      ansible.builtin.debug:
        msg: "{{ grafana_pods.resources | map(attribute='metadata.name') | list }}"
