- name: Configurar servidor com Docker, Minikube e Grafana
  hosts: grafana-servers
  become: true

  vars_files:
    - group_vars/grafana-servers.yml

  tasks:
    - name: Atualiza o cache de pacotes
      apt:
        update_cache: yes

    - name: Instala dependências necessárias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Adiciona a chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adiciona o repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Instala Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Inicia e habilita o serviço do Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Adiciona o usuário ubuntu ao grupo docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: [Aviso] #Requisição para novo login após adicionar ao grupo docker
      debug:
        msg: "AVISO: Para que o usuário 'ubuntu' tenha acesso ao Docker, é necessário sair e logar novamente na VM."

    - name: Instala Minikube
      shell: |
        curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
        rm minikube-linux-amd64
      args:
        executable: /bin/bash
        creates: /usr/local/bin/minikube

    - name: Inicia o cluster Minikube (Docker driver)
      become_user: ubuntu
      shell: |
        minikube start --driver=docker
      args:
        executable: /bin/bash
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

    # ----------------------------
    # AQUI CONTINUA SUA CONFIG DO GRAFANA (mantida)
    # ----------------------------

    - name: Clonar repositório do Grafana
      git:
        repo: "{{ grafana_repo_url }}"
        dest: "{{ grafana_repo_dest }}"
        version: main
        force: yes
        update: yes

    - name: Subir containers com Docker Compose
      shell: docker compose up -d
      args:
        chdir: "{{ grafana_repo_dest }}"

    - name: Esperar o Grafana subir
      wait_for:
        host: 127.0.0.1
        port: 3000
        delay: 10
        timeout: 60
        state: started
