---
- name: Setup completo de servidor com Minikube + NGINX + K8s
  hosts: grafana-servers
  become: true

  vars:
    docker_packages:
      - docker.io

  tasks:

    ####### SISTEMA & DEPENDÊNCIAS ########
    - name: Atualiza cache do APT e faz upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instala dependências básicas
      apt:
        name:
          - curl
          - wget
          - git
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    ####### DOCKER ########
    - name: Instala Docker
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Adiciona usuário ubuntu ao grupo docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    ####### MINIKUBE ########
    - name: Baixa binário do Minikube
      get_url:
        url: "https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64"
        dest: /tmp/minikube-linux-amd64
        mode: '0755'

    - name: Move binário para /usr/local/bin
      command: mv /tmp/minikube-linux-amd64 /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    - name: Garante permissão de execução no Minikube
      file:
        path: /usr/local/bin/minikube
        mode: '0755'
        owner: root
        group: root

    - name: Cria alias kubectl no .bashrc do usuário ubuntu
      become_user: ubuntu
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'alias kubectl="minikube kubectl --"'
        insertafter: EOF

    - name: Verifica se Minikube está ativo
      become_user: ubuntu
      shell: 'minikube status --format={{"{{.Host}}"}}'
      register: minikube_status
      ignore_errors: yes

    - name: Inicia Minikube se não estiver ativo
      become_user: ubuntu
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"
      shell: |
        newgrp docker <<'EOF'
        minikube start --driver=docker --cpus=2 --memory=4g
        EOF
      args:
        executable: /bin/bash
      when: minikube_status is defined and minikube_status.stdout != "Running"

    ####### PYTHON + K8S ########
    - name: Instala biblioteca kubernetes do Python
      pip:
        name: kubernetes
        executable: pip3
        extra_args: --break-system-packages

    ####### NGINX ########
    - name: Instala NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copia arquivo nginx.conf
      copy:
        src: "{{ playbook_dir }}/files/k8s/nginx.conf"
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: Reinicia NGINX

    ####### KUBERNETES MANIFESTS ########
    - name: Cria pasta /home/ubuntu/k8s na VM
      file:
        path: /home/ubuntu/k8s
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copia manifests do repositório para a VM
      copy:
        src: "{{ playbook_dir }}/files/k8s/"
        dest: /home/ubuntu/k8s/
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        remote_src: no
      become_user: ubuntu

    - name: Aplica todos os manifests do Kubernetes via CLI
      become_user: ubuntu
      shell: |
        for f in /home/ubuntu/k8s/*.yaml; do
          minikube kubectl -- apply -f "$f"
        done
      args:
        executable: /bin/bash

  handlers:
    - name: Reinicia NGINX
      service:
        name: nginx
        state: restarted
        enabled: yes
