---
- name: Setup Minikube em Linux (x86-64)
  hosts: grafana-servers
  become: true
  vars:
    minikube_bin_url: "https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64"
    minikube_bin_dest: "/usr/local/bin/minikube"
    docker_packages:
      - docker.io

  tasks:

    - name: Atualiza o cache de pacotes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instala o Docker
      apt:
        name: "{{ docker_packages }}"
        state: present

    - name: Baixa o binário do Minikube
      get_url:
        url: "{{ minikube_bin_url }}"
        dest: /tmp/minikube-linux-amd64
        mode: '0755'

    - name: Move o binário do Minikube para /usr/local/bin
      command: mv /tmp/minikube-linux-amd64 {{ minikube_bin_dest }}
      args:
        creates: "{{ minikube_bin_dest }}"

    - name: Garante permissão de execução ao Minikube
      file:
        path: "{{ minikube_bin_dest }}"
        mode: '0755'
        owner: root
        group: root

    - name: Cria alias kubectl="minikube kubectl --"
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'alias kubectl="minikube kubectl --"'
        create: yes
        insertafter: EOF
      become: false

    - name: Informa o usuário sobre como iniciar o cluster
      debug:
        msg: |
          Minikube instalado com sucesso! Agora execute manualmente:
            $ minikube start
          E para usar o kubectl:
            $ kubectl get po -A
            ou
            $ minikube kubectl -- get po -A
