---
- name: Setup de servidor com Grafana + Minikube
  hosts: grafana-servers
  become: true

  vars:
    minikube_bin_url: "https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64"
    minikube_bin_dest: "/usr/local/bin/minikube"
    docker_packages:
      - docker.io
    grafana_apt_key_url: https://packages.grafana.com/gpg.key
    grafana_repo: "deb https://packages.grafana.com/oss/deb stable main"

  tasks:

    ####### GRAFANA ########

    - name: Atualiza cache do APT
      apt:
        update_cache: yes

    - name: Adiciona chave GPG do Grafana
      apt_key:
        url: "{{ grafana_apt_key_url }}"
        state: present

    - name: Adiciona repositório do Grafana
      apt_repository:
        repo: "{{ grafana_repo }}"
        state: present

    - name: Instala Grafana
      apt:
        name: grafana
        state: present

    - name: Ativa e inicia serviço do Grafana
      systemd:
        name: grafana-server
        enabled: true
        state: started

    ####### DOCKER + MINIKUBE ########

    - name: Instala Docker
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Baixa binário do Minikube
      get_url:
        url: "{{ minikube_bin_url }}"
        dest: /tmp/minikube-linux-amd64
        mode: '0755'

    - name: Move binário para /usr/local/bin
      command: mv /tmp/minikube-linux-amd64 {{ minikube_bin_dest }}
      args:
        creates: "{{ minikube_bin_dest }}"

    - name: Garante permissão de execução no Minikube
      file:
        path: "{{ minikube_bin_dest }}"
        mode: '0755'
        owner: root
        group: root

    - name: Adiciona alias kubectl no .bashrc do usuário ubuntu
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'alias kubectl="minikube kubectl --"'
        insertafter: EOF
      become: false

    - name: Inicia o cluster Minikube (Docker Driver)
      become_user: ubuntu
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"
      shell: |
        minikube start --driver=docker || true
      args:
        executable: /bin/bash
