apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argocd-sa
    namespace: default
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
