apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: argocd-server
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: repo
      port: 8081
      targetPort: 8081
  selector:
    app: argocd-repo-server
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-application-controller
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8082
  selector:
    app: argocd-application-controller
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-redis
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: argocd-redis
