apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: quay.io/argoproj/argocd:v2.11.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        command: ["argocd-server"]
        args:
          - --insecure
        volumeMounts:
        - name: static-files
          mountPath: /shared
      volumes:
      - name: static-files
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-repo-server
  template:
    metadata:
      labels:
        app: argocd-repo-server
    spec:
      containers:
      - name: argocd-repo-server
        image: quay.io/argoproj/argocd:v2.11.3
        ports:
        - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-application-controller
  template:
    metadata:
      labels:
        app: argocd-application-controller
    spec:
      containers:
      - name: argocd-application-controller
        image: quay.io/argoproj/argocd:v2.11.3
        command: ["argocd-application-controller"]
        args: ["--status-processors", "20", "--operation-processors", "10"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-dex-server
  template:
    metadata:
      labels:
        app: argocd-dex-server
    spec:
      containers:
      - name: dex
        image: quay.io/dexidp/dex:v2.36.1
        ports:
        - containerPort: 5556
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-redis
  template:
    metadata:
      labels:
        app: argocd-redis
    spec:
      containers:
      - name: redis
        image: redis:7.2
        ports:
        - containerPort: 6379
