apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-conf
  labels:
    app: nginx-proxy
data:
  nginx.conf: |
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;

    events {
        worker_connections 768;
    }

    http {
        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        keepalive_timeout 65;

        server {
            listen 80;

            location / {
                return 200 'Olá, DevOps!';
                add_header Content-Type text/plain;
            }
        }
    }
