apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-env-vars
  labels:
    app: nginx-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: nginx:1.25.3
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: nginx-env-vars
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

        - name: prometheus
          image: prom/prometheus:v2.52.0
          ports:
            - containerPort: 9090
          args:
            - "--storage.tsdb.path=/prometheus"
            - "--web.listen-address=:9090"
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-custom-conf
        - name: prometheus-data
          emptyDir: {}
